# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Random thoughts
email: anavarro@achtung.es
description: > # this means to ignore newlines until "baseurl:"
    All opinions expressed here are my own personal views. Of course they do not always meet the reality.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://achtung.es" # the base hostname & protocol for your site
twitter_username: alnacle
github_username:  anavarro

# Build settings
markdown: kramdown
